### ISSUE TITLE
wrap it in a chrome extension!

### ISSUE THREAD

**Issue by smeijer** [testing-library/testing-playground#11]
I believe we can wrap this project into a chrome extension. That way people can use the thing on their own sites, without needing to copy / paste html fragments. How awesome would that be?!

---
Resources 
- https://twitter.com/kentcdodds/status/1264253036626501632?s=19
- https://twitter.com/SferaDev/status/1264264904258748416?s=19

**Comment by marcosvega91** [comment]
This is a very great feature

**Comment by MichaelDeBoey** [comment]
@benmonro created an official one: https://github.com/testing-library/which-query

**Comment by smeijer** [comment]
That's an official `testing-library` one. I'm also working on a `testing-playground` extension. It will be different, so it might be good to have both. :innocent:

**Comment by benmonro** [comment]
Cool. What features are you putting into that one?

**Comment by smeijer** [comment]
@benmonro , how about a preview? :sunglasses: 

https://twitter.com/meijer_s/status/1269703405150314498?s=20

**Comment by benmonro** [comment]
That's cool!  It does feel like we should combine them into one extension though.  Just my 2 cents

**Comment by MichaelDeBoey** [comment]
@smeijer Yours looks more like some sort of devtools & @benmonro's is more like a context menu plugin.

II think combining them into 1 thing seems indeed a good idea 🙂

**Comment by benmonro** [comment]
Yeah mine also has an elements inspector panel and adds things to the console.  Would definitely love to combine forces on this.  I think it'd be best for the community imo

**Comment by benmonro** [comment]
@smeijer i can make you admin on that repo in case that's a concern.  Let me know how we can come together on this. My goal is just to make the best experience for everyone and avoid fragmenting

**Comment by smeijer** [comment]
No worries. Let me wrap this thing up, and see where we can meet.

The biggest concern that I have with being an "official extension" isn't about being an admin or not. It's about the limitations.

In my opinion, the official one should stick to the strict recommendations. While an unofficial extension, can provide some fallback queries. Less perfect, but still workable. (`document.querySelector('.deep > .ly > .nested > .node')`)

I still haven't tried `which-query`. I should definitely do that somewhere this week. 😳

**Comment by benmonro** [comment]
That's fair.  How would you feel if I integrated some of what you've done into the official one?  I was wanting to add a devtool page and what you have here is perfect....

**Comment by smeijer** [comment]
About which parts are you thinking specifically? Just functionality / code? Or also the look and feel of testing-playground.com?

If you tell me your plans with which-query, I might submit a PR once this one is done. But having two identical extensions doesn't make a lot of sense. 

I've also added a pane to the element inspector. That's where my work in this extension started. But I moved to a dedicated panel later on. I can share a short video of that tomorrow.

**Comment by benmonro** [comment]
Yeah my plan was to build something very similar to what you have.  Perhaps just the suggestion part.  The goal if which query is to improve the a11y of the tests through the queries so I probably would leave the bottom half out (though if you want to combine them into one extension I'd be fine keeping it)

**Comment by smeijer** [comment]
I've checked out `which-query`, and it looks like I've got all the functionality ready that `which-query` has, except I offer more.

The only thing that I haven't implemented, is a context menu. Would it not make more sense to merge that functionality in the testing-playground extension?

To answer your question:

> How would you feel if I integrated some of what you've done into the official one?

To be honest, I wouldn't be thrilled. I've been working hard on this project. And ending up with two equal extensions doesn't make a lot of sense.

Here a small preview of the added sidebar panel:

![devtools-teaser-2](https://user-images.githubusercontent.com/1196524/84019801-12888180-a982-11ea-853d-32215a827524.gif)

**Comment by benmonro** [comment]
Kind of bummed to hear that.  I also worked hard on which query and shared my ideas and progress with you the whole way.  Was really hoping we could Come together for the sake of community but hey it's your decision.

**Comment by smeijer** [comment]
I understand. And I appreciate the work you've done by implementing the query suggestions from testing-playground into the core of testing-library. I also like that testing-playground has [inspired you](https://twitter.com/benmonro/status/1264549790181756928) to turn `which-query` into an extension (instead of the query suggestions lib).

I still believe it's possible to come together. As I said earlier, wouldn't it make sense to merge the functionality of `which-query` into `testing-playground`, and continue working on this one instead?

**Comment by smeijer** [comment]
Closed by #145
