### ISSUE TITLE
fix: use `getSuggestedQuery` from `@testing-library/dom`

### ISSUE THREAD

**Issue by smeijer** [testing-library/testing-playground#134]
#113 already implemented this partially. But I noticed that it isn't applied yet in the `ResultSuggestions` component (the blue buttons on the bottom left)

![suggestions](https://user-images.githubusercontent.com/1196524/84401165-3dcdd380-ac03-11ea-8815-f56138ce9bd1.gif)

**Comment by marcosvega91** [comment]
I'll fix it :)

**Comment by smeijer** [comment]
Wait for this one: https://github.com/testing-library/dom-testing-library/pull/627 :innocent:

**Comment by smeijer** [comment]
Well, you didn't need to wait long. 😁🎉

**Comment by marcosvega91** [comment]
Hahahaha ok. I'll update the library and fix the code

**Comment by marcosvega91** [comment]
Do you have any idea how to solve problem with `contentWindow` that is null? When I call `getSuggestedQuery` I have an error because the element is inaccessible.
The target element is taken from `iFrame`. We need a way to replace it with the one from `Preview` component. Do you have any idea?

**Comment by smeijer** [comment]
I think we shouldn't be taking it from the iframe. Instead, we can create an in memory div, and simulate the environment there.

The element can be selected with the cssPath. 

(from my phone) 

```js
const view = document.createElement('div');
view.innerHTML = markup;
const target = view.querySelector(el.cssPath.toString());

const query = getSuggestedQuery(target, 'get', ...
```
