### ISSUE TITLE
Move to testing library org?

### ISSUE THREAD

**Issue by kentcdodds** [testing-library/testing-playground#146]
Hi @smeijer,

This is amazing work! It's awesome. I'd like to invite you to officially join the testing library maintainers within the testing library GitHub org. This is totally up to you. If you'd prefer to keep it under your username that's fine. The benefit of moving it to the org is that it makes the project more official and contributions and collaborations are more plentiful.

Let me know, and I'll help it happen.

**Comment by smeijer** [comment]
Hi @kentcdodds!

Thanks. This means a lot!

I'll reach out to you later today, for some questions regarding on how being part of such a big family works.

This is very exciting to me. I've never expected this project to take of so fast.

Thanks again! Much appreciated. 😊

**Comment by smeijer** [comment]
@kentcdodds I couldn't find a way to contact you in person, so I've send an email to your github public email. Not sure if you read that account, so I thought I let you know.

**Comment by marcosvega91** [comment]
I think that you can eventually contact him on his  discord

**Comment by smeijer** [comment]
I tried. Direct message is disabled

**Comment by kentcdodds** [comment]
The email is fine. Will respond as soon as I'm able. Thanks!

**Comment by smeijer** [comment]
Update; this is going to happen! 🎉😎

**Comment by kentcdodds** [comment]
Alright, you've been added to the org and to a team called "Testing Playground". You have "owner" status on that team so you should be good to go. Let me know if you have any trouble. Thanks and welcome to the team!

**Comment by smeijer** [comment]
# The :frog: has left the building!

Thanks @kentcdodds. For the invite, the input, and all the kind words.
