### ISSUE TITLE
Remove state from url

### ISSUE THREAD

**Issue by smeijer** [testing-library/testing-playground#153]
Once #151, #152 and #54 are completed, we might be able to remove the state from the url.

**Comment by MichaelDeBoey** [comment]
Is this going to impact [`gatsby-remark-embedder`](https://github.com/MichaelDeBoey/gatsby-remark-embedder) in any way? 🤔

https://github.com/MichaelDeBoey/gatsby-remark-embedder/pull/124

**Comment by smeijer** [comment]
No, an explicit share button will be added in #54. Just copy/paste the URL from there.

We'll make sure that we are backwards compatible.

**Comment by smeijer** [comment]
Closed by #232.
