### ISSUE TITLE
Chrome Extension permissions needs to be fixed for approval

### ISSUE THREAD

**Issue by smeijer** [testing-library/testing-playground#175]
The chrome extension was rejected due to:

> **User Data Privacy**
>
> Use of Permissions
Request access to the narrowest permissions necessary to implement your Product’s features or services. If more than one permission could be used to implement a feature, you must request those with the least access to data or functionality.
>
> Don't attempt to "future proof" your Product by requesting a permission that might benefit services or features that have not yet been implemented.

All help would be appreciated!

**Comment by AmySteam** [comment]
Hi there, I have been helping chrome developers pass the chrome web store review process, and after looking at your code, you actually don't need activeTab. 

The activeTab permission gives an extension temporary access to the currently active tab when the user **invokes** the extension. For example with the following actions
[Invoking activeTab](https://developer.chrome.com/extensions/activeTab#invoking-activeTab)
The following user gestures enable activeTab:

- Executing a browser action
- Executing a page action
- Executing a context menu item
- Executing a keyboard shortcut from the commands API
- Accepting a suggestion from the omnibox API

Hope this helps,
[Amy](https://www.youtube.com/channel/UCVj3dGw75v8aHFYD6CL1tFg)
@jackandamydev DM if you have any questions

**Comment by smeijer** [comment]
Thanks @AmySteam! 

Your explanation has been helpful. I don't understand a thing about the ActiveTab, and I'm confused that the extension works without either the `<all_urls>` or the `ActiveTab` permission. It makes me wonder why so many extensions request them (and still pass the review process).

I've resubmitted the extension with the permissions as below. 

The content script still triggered a `host permission`, so they'll do another "deep investigation". Let's hope that it passes this time.

```js
{
  permissions: ['clipboardWrite'],
  content_scripts: [{
    matches: ['<all_urls>'],
    js: ['content-script/contentScript.js'],
    run_at: 'document_start',
  }],
}
```

**Comment by AmySteam** [comment]
On the content script matches, do you really need all urls? This includes the file:/// schema. 
If they reject it again, you might want to limit it to https:// and http://.

Hope your extension gets published!
Amy
[Chrome Extension Tutorial Channel](https://www.youtube.com/channel/UCVj3dGw75v8aHFYD6CL1tFg/)

**Comment by smeijer** [comment]
I thought about that. But if we limit those urls, we are limiting the options the developers have. I hope we don't need to go that way.

**Comment by MichaelDeBoey** [comment]
I think this one can be closed now? 🤔
https://twitter.com/meijer_s/status/1275736530175307780

**Comment by smeijer** [comment]
Indeed it can :tada: :partying_face: 

@AmySteam, thanks for sharing your knowledge with me :heart:
