### ISSUE TITLE
ReadMe Contributing Section has wrong getting started commands

### ISSUE THREAD

**Issue by connorProgrammes** [testing-library/testing-playground#180]
## Bug Report 🐛

<img width="963" alt="Screen Shot 2020-06-16 at 8 20 22 PM" src="https://user-images.githubusercontent.com/66570218/84851399-fd10f880-b00e-11ea-8f6d-fea7582a6eb8.png">

As far as I can tell this seems like a bug as there is no command for just `npm ci`

## Suggested solution 🔦
I believe this is supposed to be `npm run ci:test`?

I am happy to fix this if this is what is intended to be in the readME 😃

**Comment by delca85** [comment]
Hi @connorProgrammes !

Thanks for the comment.
Actually `[npm ci](https://docs.npmjs.com/cli/ci.html)` is a command offered by `npm` so it must not be entered in `package.json`.

**Comment by smeijer** [comment]
@connorProgrammes, I'm closing this one, as it's not an issue with the code. The explanation of @delca85 is spot on!

If you still have any questions, please feel free to let us know.
