### ISSUE TITLE
Testing Playground crashes when all content in `MarkDownEditor` is erased

### ISSUE THREAD

**Issue by connorProgrammes** [testing-library/testing-playground#192]
## To Reproduce ✔️

When erasing all content from the `MarkUpEditor` the whole page crashes. I have provided both a GIF and a stack trace below to further explain
**GIF**

![playground_bug](https://user-images.githubusercontent.com/66570218/84978871-dfad5e80-b0e2-11ea-8ed4-62b6d09a2a29.gif)

**Stack Trace**

<img width="437" alt="Screen Shot 2020-06-17 at 9 39 34 PM" src="https://user-images.githubusercontent.com/66570218/84978946-0e2b3980-b0e3-11ea-92c5-a9716ce3c9c2.png">

## Expected behavior 🤔

I expect the editor to clear so I can begin writing my own HTML and testing those instead of the predefined ones you get when visiting the site.

## Suggested solution 🔦
Open for discussion

## Your Environment 💻

- _browser_: Chrome Version 81.0.4044.138
- _os_: Mac

**Comment by marcosvega91** [comment]
Hi @connorProgrammes thanks for opening the issue 😄 

This issue was solved in a previous commit, if you go [next-version](https://develop.testing-playground.com), the bug is not present. Have you updated your develop branch with upstream?

**Comment by smeijer** [comment]
I've updated production as well. Thanks for the report :+1:
