### ISSUE TITLE
support custom `testid` in the Chrome Extension

### ISSUE THREAD

**Issue by smeijer** [testing-library/testing-playground#213]
## Summary 💡

The title says it all.

## Motivation 🔦

https://twitter.com/wescopeland_/status/1275800945331441668?s=20

**Comment by delca85** [comment]
Hey!
Could I maybe have an example of a custom testId that the Chrome extension should support?
Thanks!

**Comment by smeijer** [comment]
Every possible element attribute.

https://testing-library.com/docs/dom-testing-library/api-configuration

**Comment by delca85** [comment]
Ok, I got it. Thank you very much!

**Comment by delca85** [comment]
I could give it a shot.
I have two question about the implementation:
1. should we enable this feature in `testing-playground` too?
2. if you have already thought about this: in order to retrieve the desired attribute to be used as `testId` should we add an input somewhere where the user could insert it?

**Comment by smeijer** [comment]
1. Yes, I think we should keep the web version and the chrome version as equal as possible. That way a user could just copy/paste code from his tests (debug output) to the web version, and share the link with others to get some advice.

2. Yes, we would need an `input`. I have some idea's about the interface, but I haven't figured it out exactly. I think we need to add a settings modal similar to how react-devtools does it. The settings modal for the web version can follow later on, as long as the technical implementation (the id-attribute config) works on both.

    If we need a library for the modal, we can use `https://reacttraining.com/reach-ui/dialog`

**Comment by delca85** [comment]
Ok, I think I have understood.
If it sounds good to you, I could start adding a settings modal to the extension in which a user could insert the attribute to be used as custom test id.

**Comment by smeijer** [comment]
Sounds great @delca85.

**Comment by smeijer** [comment]
@delca85, I'm working on an interface update to support a setting modal. So don't worry too much about where you're going to place that `input`. Just focus on figuring out how we can configure testing-lib to apply that setting.

![image](https://user-images.githubusercontent.com/1196524/86150740-141b1480-bafe-11ea-85c9-0eeeb4ea9d56.png)

**Comment by delca85** [comment]
@smeijer, great! I have already implemented the functionality but I still have to apply style to the modal. If it's ok for you I could push tonight the code I have and later we could merge our work.

**Comment by smeijer** [comment]
Sounds good to me @delca85

**Comment by smeijer** [comment]
closed by #213
