### ISSUE TITLE
Page breaks with compound aria-labelledby example

### ISSUE THREAD

**Issue by timkindberg** [testing-library/testing-playground#214]
## Bug Report 🐛

Playground crashes when attempting to target an input with multiple labels used in aria-labelledby

## To Reproduce ✔️

1. Paste this into the HTML box
```html
<div id="a">One</div>
<div id="b">Two</div>
<input
  type="text"
  aria-labelledby="a b"
/>
```
There are various ways to trigger the crash
1. Click the input in the preview
2. Try to manually construct a valid selector in the bottom left panel

## Expected behavior 🤔

No crash

## Suggested solution 🔦

Error suggests that maybe you are constructing a selector that causes the issue:
![image](https://user-images.githubusercontent.com/168046/85593353-f5f07880-b614-11ea-9d31-eee34b773c21.png)

## Your Environment 💻

- _browser_: Chrome
- _os_: Mac

**Comment by marcosvega91** [comment]
Hi @timkindberg 
thanks for reporting this issue 😄 . 
It is regarding to [#545](https://github.com/testing-library/dom-testing-library/issues/545). 
Unfortunately at the moment this kind of query is not supported yet.

I'll fix on this side in a while 👍
