### ISSUE TITLE
Add a tooltip for the extension buttons

### ISSUE THREAD

**Issue by kentcdodds** [testing-library/testing-playground#218]
I'm not sure what these do:

![image](https://user-images.githubusercontent.com/1500684/85620149-9dbf7380-b620-11ea-93d7-5fab706966de.png)

A tooltip with a short description/title would be nice :)

**Comment by smeijer** [comment]
@kentcdodds , it should be there.  If it's not working, it's a bug.

Which browser do you use? The video below is Chrome on Ubuntu.

![tooltip](https://user-images.githubusercontent.com/1196524/85629664-8e691600-b672-11ea-90d0-3019af1578a8.gif)

**Comment by kentcdodds** [comment]
I wasn't patient 😅
