### ISSUE TITLE
Extension hides buttons in jira? 

### ISSUE THREAD

**Issue by smeijer** [testing-library/testing-playground#225]
This issue is originating from the chrome webstore. 

I doubt that the extension can be causing this, but we should verify. 

On the support tab:
https://chrome.google.com/webstore/detail/testing-playground/hejbmebodbijjdhflfknehhcgaklhano

![Screenshot_20200628-231422](https://user-images.githubusercontent.com/1196524/85958368-5f65e380-b995-11ea-855c-4667431d6e8d.jpg)

**Comment by marcosvega91** [comment]
I have tried to replicate this, in jira you can only add comments but I don't see a way to reply to an existent comment

**Comment by smeijer** [comment]
> I don't see a way to reply to an existent comment

Is that with, or without the extension installed? 😇

**Comment by delca85** [comment]
> > I don't see a way to reply to an existent comment
> 
> Is that with, or without the extension installed? 😇

According to me even without the extension installed.
