### ISSUE TITLE
Can't disable "select element" mouseover

### ISSUE THREAD

**Issue by rbusquet** [testing-library/testing-playground#228]
## Bug Report 🐛

Can't disable mouse over hint by clicking on the "select element" button in the chrome extension:

![Jun-30-2020 23-18-50](https://user-images.githubusercontent.com/7198302/86199429-198d5480-bb28-11ea-9fff-68739acc863c.gif)

## To Reproduce ✔️

1. Click the "select element" button on the chrome extension
2. See mouse-over triggers changes in the code editor for hints
3. Click "select element" again
4. Mouse-over behavior continues, even after changing tabs/closing dev tools

## Expected behavior 🤔

Mouse over overlay behavior is togglable.

## Suggested solution 🔦

Not a lot, don't have much experience developing for chrome extensions

## Your Environment 💻

- _browser_: Chrome
- _os_: Mac

**Comment by marcosvega91** [comment]
Hi @rbusquet thanks for spotting this :).

I have fixed the issue #229
