### ISSUE TITLE
support query suggestions for select options

### ISSUE THREAD

**Issue by smeijer** [testing-library/testing-playground#237]
## Summary 💡

When I select `audi` from the list of `cars`, I want the playground to give me the right query.

## Examples 🌈

```html
<label for="cars">Choose a car:</label>

<select name="cars" id="cars">
  <option value="volvo">Volvo</option>
  <option value="saab">Saab</option>
  <option value="mercedes">Mercedes</option>
  <option value="audi">Audi</option>
</select>
```

```js
screen.getByRole('option', {
  name: /audi/i
});
```

The query above works, but can not be constructed by using the preview pane + clicking on elements.

## Motivation 🔦
https://discordapp.com/channels/723559267868737556/724762529259061308/727609068067225681

**Comment by delca85** [comment]
Hey @smeijer !
Could I give it a shot or are you already working on it?

**Comment by smeijer** [comment]
@delca85 , no-one has claimed this yet. So please take your shot :+1:

**Comment by delca85** [comment]
@smeijer maybe could we close it because #252 enabled it?
