### ISSUE TITLE
Clicking on Preview pane does not close any menu like playground or settings on develop environment

### ISSUE THREAD

**Issue by delca85** [testing-library/testing-playground#243]
## Bug Report 🐛

Like said in title, playing with  https://develop.testing-playground.com/  I found out that once a menu from toolbar like `playground` or `settings` is opened, clicking on `Preview` pane does not close it. While if I click on another pane (`MarkupEditor`, `QueryEditor` or `Result`) closes it.

## Expected behavior 🤔

I expected that clicking outside the menu but inside `Preview` would close the menu. I know this is not a severe issue :)

## Your Environment 💻

- _browser_: Chrome
- _os_: Mac

**Comment by smeijer** [comment]
I'm not sure what exactly causes this. Maybe clicks in an iframe aren't propagated back to the parent document?

Anyway, I don't think it's worth postponing the release for this issue.

**Comment by delca85** [comment]
I totally agree!

**Comment by aganglada** [comment]
Related to an issue from reach-ui, we have exactly the same behaviour https://github.com/reach/reach-ui/issues/566

![Screenshot 2020-11-11 at 09 55 33](https://user-images.githubusercontent.com/922348/98797133-16727100-2404-11eb-982e-06d5ed8e967a.png)

**Comment by aganglada** [comment]
@smeijer I will keep track of reach/reach-ui#566 to update our version
