### ISSUE TITLE
In develop environment role queries not appear in ResultQueries

### ISSUE THREAD

**Issue by delca85** [testing-library/testing-playground#246]
## Bug Report 🐛

On  https://develop.testing-playground.com/, clicking on an `input` element, the `getByRole` query is rightly inserted (and evaluated) in `QueryEditor` but it does not appear in `ResultQueries`.
Clicking on a `button` element does not reproduce this bug, the `role` query appears in `ResultQueries`.

<img width="1678" alt="Screenshot 2020-07-05 at 16 01 56" src="https://user-images.githubusercontent.com/4076043/86534501-397e9880-bed9-11ea-8b66-357a00448d2d.png">

## To Reproduce ✔️

1. inserted markup
2. select an input element

## Expected behavior 🤔

I expected the `getByRole` query would appear in `ResultQueries` as it happens in the `button` case.
## Your Environment 💻

- _browser_: Chrome
- _os_: Mac

**Comment by delca85** [comment]
I just found [this](// for inputs, the role will only work if there is also a type attribute) comment. The inserted markup indeed had the `type` attribute specified (it was `email`) but it does not work anyway while if I set it to `textbox` the query is rightly suggested in `ResultQueries`.

**Comment by smeijer** [comment]
I feel like not all the parts of the playground are using suggestions generated by testing-library/dom. That should make cases like these impossible.

**Comment by delca85** [comment]
Ok, I got your point but I think that maybe we could improve the playground suggestion in case of `input` with a defined `type` even if it is not `text`.

If I am not wrong, [this](https://github.com/testing-library/testing-playground/blob/989b35d038cfe774cba511ef351ffc8a2ba4d33a/src/lib/queryAdvise.js#L21) is where we create the `role` suggestion.
In case of we are evaluating an `input` element the `getRole` by [dom-accessibility-api](https://github.com/eps1lon/dom-accessibility-api/blob/main/sources/getRole.ts) is called only if the `type` attribute is `text`. I think that we could call `getRole` anyway because `dom-accessibility-api` manages every possible value of an `input` element (an undefined value too).

If it sounds reasonable to you I could open a PR.

**Comment by smeijer** [comment]
Sounds good to me.
