### ISSUE TITLE
Suggested query not updating when clicking an element

### ISSUE THREAD

**Issue by ljosberinn** [testing-library/testing-playground#268]
## Bug Report 🐛

Using the example code, clicking any element in the top right corner will update the bottom left, but not the bottom right:

![image](https://user-images.githubusercontent.com/29307652/90230777-5bddcd00-de1a-11ea-9110-6dd860169121.png)

As soon as you type something, even only a space, in the bottom left area, bottom right will update appropriately.
Notice the meta info about the element below bottom lefts content is still on the initial selection of the submit button, although I already clicked the password label.

## To Reproduce ✔️

1. go https://develop.testing-playground.com/
2. unregister service worker & hard reload with cache cleared
3. click any element other than the default

## Expected behavior 🤔
The bottom right corner should update automatically. I think this worked in the past, too.

## Suggested solution 🔦
Couldn't dig into the code directly right now but looks like some hook isn't updating based on the click selection, although the text content of the area changes:

![image](https://user-images.githubusercontent.com/29307652/90231255-2f768080-de1b-11ea-98d9-00119786d9f0.png)

## Your Environment 💻

- _browser_: Chrome
- _os_:  Windows

**Comment by smeijer** [comment]
This indeed worked in the past. I don't have the time at this moment to dive in either, but I suspect I caused this with #264.

**Comment by ljosberinn** [comment]
Can confirm, it was that commit. Looking into alternative solutions now.

**Comment by smeijer** [comment]
Thanks for looking into it!

**Comment by smeijer** [comment]
@ljosberinn, update is on the way.

**Comment by ljosberinn** [comment]
oh I was looking in entirely different places, e.g. trying to skip state update in reducer if the expression is identical 😢 honestly felt a bit lost in there as it changed significantly since I last contributed - glad it's sorted!

**Comment by smeijer** [comment]
yeah, I can imagine you feeling lost.

But anyway, this fix has landed in production. Let me know if it's still bugging?

**Comment by ljosberinn** [comment]
Works like a charm 😎
