### ISSUE TITLE
Using the suggested query by text breaks when the text includes parenthesis

### ISSUE THREAD

**Issue by gndelia** [testing-library/testing-playground#271]
## Bug Report 🐛

The "Suggested Query" box breaks when trying  to load a `getByText` query if the text includes parenthesis `()`. I assume this are not being escaped in this scenario, but they are when showing the example in `getByRole`

## To Reproduce ✔️

[playground link](https://develop.testing-playground.com/gist/bd99c6876b08be42f2df30c040f43608/a8bc14ec018ddf4aeaf636f6cf2af8caa9d478d2)

it's a simple HTML with the following content

```html
<h1>some text (and note)</h1>
```

the (correct) suggested query is 

```js
screen.getByRole('heading', {
  name: /some text \(and note\)/i
})
```

The "suggested box" shows `getByText` as a clickable option. However, when I click it, I get

> // sorry, I failed to provide something useful

and the suggestion box disappears

## Expected behavior 🤔

It should show

```js
screen.getByText(/some text \(and note\)/i)
```
in the query box (bottom left). If I type it manually it works, and it suggests the `getByRole` as before, and I can click it. Clicking again the `getByText` breaks

## Suggested solution 🔦

Not sure, I'd have to dig the code 😅  I'd like to take this bug if possible. I guess other regex characters should be escaped as well

## Your Environment 💻

- _browser_: Chrome 85
- _os_: Windows 10

**Comment by marcosvega91** [comment]
Hi @gndelia thanks for reaching us 😄 .

It was a problem with a previous version of @testing-library/dom. It'll be fixed when we'll release a new version of testing-playground.

The problem was that the regex were not escaped.

Stay tuned 👍

**Comment by marcosvega91** [comment]
A new version with the fix has been released ☺️
