### ISSUE TITLE
turn it into a progressive web app (PWA)

### ISSUE THREAD

**Issue by smeijer** [testing-library/testing-playground#29]
This would enable offline usage. As the playground already is a single-page app, it shouldn't be that difficult to add?

**Comment by marcosvega91** [comment]
I've found this package https://www.npmjs.com/package/parcel-plugin-pwa-manifest

**Comment by smeijer** [comment]
We already have a manifest, although that plugin looks nice with the icon generation :). 

I think that the most time-consuming part of this ticket would be the creation of the service worker.

**Comment by marcosvega91** [comment]
@smeijer I think we can close this right?

**Comment by smeijer** [comment]
Closed by #80
