### ISSUE TITLE
Cursor jumps to the very beginning of the editor on pasting a copied string

### ISSUE THREAD

**Issue by vasilii-kovalev** [testing-library/testing-playground#297]
## Bug Report 🐛

Cursor jumps to the very beginning of the editor on pasting a copied string.

Before pasting:
![image](https://user-images.githubusercontent.com/10310491/99145109-de299780-267c-11eb-9a8d-ec61fe17bcd1.png)
After pasting:
![image](https://user-images.githubusercontent.com/10310491/99145123-fa2d3900-267c-11eb-8436-35bbb46d682d.png)

Reproduced both in markup and query editors.

## To Reproduce ✔️

1. Copy any string from somewhere
2. Go to the site
3. Paste the string to markup or query editor via `Ctrl + V` or context menu.

## Expected behavior 🤔

Cursor is placed right after the last pasted character

## Suggested solution 🔦

Maybe it can help: https://egghead.io/lessons/react-preserve-cursor-position-when-filtering-out-characters-from-a-react-input

## Your Environment 💻

- _browser_: Chrome 86.0.4240.198
- _os_: Windows 10

**Comment by vasilii-kovalev** [comment]
P.S.: It seems the link from the bug report template (https://develop.testing-playground.com/) doesn't work.
![image](https://user-images.githubusercontent.com/10310491/99145290-9f94dc80-267e-11eb-913f-7fc5c8d481ae.png)

**Comment by smeijer** [comment]
Thanks for the report @vasilii-kovalev. Both issues should now have been fixed.
