### ISSUE TITLE
`level` option of getByRole is not respected in Testing Playground

### ISSUE THREAD

**Issue by ddehart** [testing-library/testing-playground#305]
## Bug Report 🐛

Testing Playground does not respect the [level](https://testing-library.com/docs/dom-testing-library/api-queries/#level) option of getByRole.

On https://develop.testing-playground.com:

### `undefined` using `screen.getByRole('heading', {level: 1})`

![level-option](https://user-images.githubusercontent.com/901215/100552429-263be300-3255-11eb-9144-cad98c60caa3.png)

### `Array` with two elements returned using `screen.getAllByRole('heading', {level: 1})`

![getallbyrole-with-level](https://user-images.githubusercontent.com/901215/100552488-829f0280-3255-11eb-8a4d-f1b7f116a6e3.png)

## To Reproduce ✔️

[`undefined` using `screen.getByRole('heading', {level: 1})`](https://develop.testing-playground.com/gist/a0b97897a926d7c421192a78d90d5649/9235646da73af764d6f9839ffba8230bb3a0b5fd)

[`Array` with two elements returned using `screen.getAllByRole('heading', {level: 1})`](https://develop.testing-playground.com/gist/e7c39ada1a386e6f87eefa3de88844bf/402515df46dc3d8bc99b1985a48e6aff07c1d10e)

## Expected behavior 🤔

* `undefined` case: I expected the query to return `<h1> This is a level-1 heading </h1>`
* `Array` case: I expected the query to return an array with only the `<h1>` element

## Suggested solution 🔦

The `level` option was added in [dom-testing-library v7.23.0](https://github.com/testing-library/dom-testing-library/releases/tag/v7.23.0). It looks like testing-playground is using [v7.22.5](https://github.com/testing-library/testing-playground/blob/32be0f46419b00ad8adc382be0b29953ec47158e/package.json#L45).

## Your Environment 💻

- _browser_: Chrome
- _os_: Linux

**Comment by smeijer** [comment]
Thanks! Are you willing / able to submit a PR?

**Comment by ddehart** [comment]
@smeijer I'll give it a shot!
