### ISSUE TITLE
Option to disable pointer events in events tab

### ISSUE THREAD

**Issue by balavishnuvj** [testing-library/testing-playground#309]
## Summary 💡

testing-playground released an awesome feature to look at the events that were performed. It would be great to have an option to disable event like 
- mouse move (in and out)
- pointer move

As these events would just clutter the events tab.

Happy to help :)

**Comment by marcosvega91** [comment]
Hi @balavishnuvj i think that it should be fine, a nice improvement btw. Maybe we can disable by default some noise events, that could be enabled if someone need. 👍🤩

**Comment by delca85** [comment]
Hey @balavishnuvj, I totally agree with @marcosvega91. In #171 there was a list of some event types that should be disabled by default.
Maybe we could use the same list!

**Comment by smeijer** [comment]
Closing as duplicate of #171
