### ISSUE TITLE
Query input/output non-functional

### ISSUE THREAD

**Issue by ddehart** [testing-library/testing-playground#314]
## To Reproduce ✔️

1. Visit https://testing-playground.com/
2. Change the `getByRole` query to any selector other than `'button'`

![testing-playground](https://user-images.githubusercontent.com/901215/101294736-826bad80-37e7-11eb-9a74-94a4017d99c4.gif)

## Expected behavior 🤔

I expect `QueryOutput` to change based on my query

## Your Environment 💻

- _browser_: Chrome
- _os_: Linux

**Comment by marcosvega91** [comment]
Hi @ddehart thanks for raising this :).

I can confirm the bug. Do you wanna work on a fix? With e2e now we can create a test case for the issue and then fix. 
Thanks a lot :)

**Comment by smeijer** [comment]
For reference, it's 351c6ffd that broke this (PR #296)

**Comment by delca85** [comment]
> For reference, it's [351c6ff](https://github.com/testing-library/testing-playground/commit/351c6ffdccf10570f741b201ee4ea2495af347a2) that broke this (PR #296)

Yes, I confirm that. In `PlaygroundPanels` the query `value` is update while  the `result` value not.

**Comment by delca85** [comment]
In my opinion, the error is somehow related to the usage of `Suspense` in `PlaygroundPanels`, removing that component the result is updated when a new query is inserted.
https://github.com/testing-library/testing-playground/blob/fb43e61ae98f4ca07f6a18a41be70c4939dc17ea/src/components/PlaygroundPanels.js#L46

**Comment by smeijer** [comment]
That's a great finding @delca85. Thanks! Can you submit a PR?

**Comment by delca85** [comment]
I was wrong, this bug was not due by `Suspense`. I fixed it passing `state` and `dispatch` as props to `PlaygroundPanels` instead of making it retrieve them through `usePlayground` hook.
