### ISSUE TITLE
Support query-extension queries

### ISSUE THREAD

**Issue by th3fallen** [testing-library/testing-playground#341]
## Summary 💡

I would love to be able to use our queries from https://github.com/tjefferson08/query-extensions
specifically `screen.getBySelector()`

## Motivation 🔦
more over supporting other custom queries somehow would be really amazing if possible.

**Comment by smeijer** [comment]
Thanks for the suggestion. At this moment, "query-extensions" is not something I'd like to support in testing-playground.  

Regarding the `getBySelector`, it sounds to me that `container.querySelector` is the same?
