### ISSUE TITLE
Extension breaks make.com app

### ISSUE THREAD

**Issue by dimadk24** [testing-library/testing-playground#342]
## Bug Report 🐛

Cannot use [make.com](https://make.com) (formelly [integromat.com](https://integromat.com/)) with testing playground extension enabled.
Pretty weird that this extension may break some websites, but it does. 
Their app after login with testing playground enabled: https://imgur.com/a/te01JZZ
With testing playground disabled (off in [chrome://extensions](chrome://extensions)): https://imgur.com/a/lsyztCr

## To Reproduce ✔️

Install testing playground extension https://chrome.google.com/webstore/detail/testing-playground/hejbmebodbijjdhflfknehhcgaklhano?hl=ru
Sign up for https://make.com (I've reproduced this with a new clean account in incognito with only testing playground extension enabled)
Proceed to their app

Result: error somewhere in testing playground extension code.
Logs: https://pastebin.com/YaiqrfWP

## Expected behavior 🤔

Their app works: https://imgur.com/a/47A2IFs

## Your Environment 💻

- _browser_: Chrome 100.0.4896.127 (Official Build) (64-bit) 
- _os_: Linux Ubuntu 20.04 KDE

**Comment by smeijer** [comment]
Hi! Thanks for the report. Is this still the case? I fail to reproduce it.

<img width="1576" alt="image" src="https://user-images.githubusercontent.com/1196524/170883300-ecd77bde-79a0-488c-94cb-79630f77ac48.png">

**Comment by dimadk24** [comment]
Yes, it works now. It seems one of the parties has fixed something. Thanks for the checking.
