### ISSUE TITLE
Application in thinking state

### ISSUE THREAD

**Issue by jan-willem-baart** [testing-library/testing-playground#347]
## Bug Report 🐛

When using a link from screen.logTestingPlaygroundURL() of @testing-library/angular the Testing-playground.com environment is empty and [this image](https://testing-playground.com/code_thinking.299ea641.png) is shown in the right two fields.

## To Reproduce ✔️

Only reproducible locally where the generated link is functional above a certain user.click function but fails below that line.

## Expected behavior 🤔

A functional Testing-playground.com environment loaded with the application.

## Suggested solution 🔦
Some kind of error why it failed would be nice. Currently some kind of empty state is shown which doesn't indicate if the link is erroneous, the application where the link was generated is in error state etc 

## Your Environment 💻

- _browser_: Chrome
- _os_: Mac
- _any other relevant information_

**Comment by jwbaart** [comment]
It magically started working again. I'll update when it happens again!

**Comment by jwbaart** [comment]
@smeijer and they are back again. Are you able to see why it fails? https://testing-playground.com/#markup=DwEwlgbgBGILwCIBOB7FAXADAqA7A5gLQQCmSAzmCrogIwBMAdLYwKw4CGSYHhAFrBAkaCdEgCuJBAD5gqcejKEUCgDYl0s+YqTK1G2QHptSlenWbgHAA7XCAdxRIA1gGNhOwqrDl0UV6oc5OSIBIS+XIRguORkiiAycmam+pbGybpmFrIAhISErtToHNFKhLIAthzohOhoqgBGXP6BwYhVNXUojc0gXM5QHbX1TbqUBOqEqPaJ4NABQSEIAGZgqjpQq+tl4OQcDeoJldVRhbhQqOqIYBX4OAttCENgZ3gYSBwxgYqD1WQ8qlO1HIvxqL2ohFwKAK3ScnG4vAEICEIjEkhwfWKhGeZ1qAE9rCREMsijIqtZyAB9PgoCokSmOFzAQw46jHGqxdSuPyXIkIQoVBooIUAD3hPEIHAUKAF1gsfKhuCkUC4Er4QWsKGs4msiDRyoeSyGnJI3LwRHQMQKtAALJhCJhQeESFyart9ocnSbuYQSBVrOg8ebwsVdNFYkh4jgwkgSMtXYR3QcSPBRBJlareIEGi7Dg08e0Tt6ahAOKpJIRaDhYIWOS7TTVsFBig1okIRYhK+LeCQRdZPkJU8sy7Fu1MSABHcRgWNDkcZhGJnwelN69Nj6Kl7xz1Sj2RzfwgZzKUhIQJ45TcfDRRD3VpGov1n1iMD4fBkYOW8jWu0O2aQFpFlrZ0Ey3SRPytVxbXtJsYzjBMwnIewwHQVw+DXdEYFTY0nxLMsKyrWRyH7c5DWA4tCDlDh3BpVQhCQL1cOxaIvFKCDvyg39HUQ0MohiOIU0SQxiM+XJ8lbXBwAIEIAG8ACgEDg+MG0hIgkJQtCCiCKQAC4oDTdE5IAX3yMTCAkqT8FkhSlIQtTkNQvgtNHPSVnnBBjNM5k5n3ACyKeR8Ey4aYHA+WwPzCL8fxg-95nvcimOClB7HY6K-yMHzvMgDLsuAPJzLbaIrLgeTFKIWNlJ9FBlmWWIajxBBXOwTzymZHDXRyiBfLioCVjWDYtk8Jc9mTI5gFZc5eWuW4716ia3jET5yG+EhQX+MsgRiJ1wVwSFoUKVQ4RVRckRRDDlUxXgJvxQliVJaRrFjVwfCoXBKSqXBxGHblxG4Ag2pOHb2RAhsLm6PkBSFUUxylOpZXlUJqAXNUNS1HVztmx52tByLIOgytGITJNPWxn0-QDIMeMicMBISYMKqJ5dRox46JWzXMU3zBLQPwkhCAAZmrbDApU+gcBbNte07KtWZ7PsB1XNzd2R3hYynGdFeHZWx2JxX9Q3XAtxrJW91APyjxPMhz0vV8bwQTGHzrBMXzfCKLTx39CLNnqsZFn0wNW3GOPxmXbJUxCHLQlnjdJvDyz5wWiJIwDfadlSqJo7p6MJlSKhY7wlVSzj7VoYMIjDfjI0EowRNwMyLKK6yyvHSqagjjSnNcbTGv0-WWvrwrpJKmzyvg8P7I75zdP0rXR37rKuu9lPHZBn0kvsUKbEJBig7Sr2D382PJSQaYi5DoTMsMS-Mvyhuh9KsOqpqurCAapqPJM1qWT9tJL6GLoehIGBgA0Yy9gIgOaEMespZ0CvUIAAL3oE6CBYwiqTGmLFMBCBYhcDQokaI2o-AZxILReiiAADKJBcF8BwB0AhChbyggAbA3UCBKHUKgL4P6+BOE0nEHRFU5gqG+CgDmKA-N-Dqg+NyMg5AHbAXoTUesdJcB+CGCSJAFRCCrBdCASU0otiAjOGIboyD6gsNqFed8O8iDiFUSoNCKZgxGxAIeY8igRQ1B0XRfRdRDHYmoChJwTjXAWxJK4cQsRXGhOPM4EgeIhRcD0eEyJTiwjgEjA1emY8fTENIWQChVCkB4Oya3bEJBggcHfIUjhXCiq8JUAI6o6ggh+AaDrCprhuA5hAFzfkFshDkC6WAHp+ZymVPfH+NxiZOndM5heGkvhGEx0BrgQhUzLqUUCJnOiBS2FFJKZmPiLjiTuVluOdWs5Tna1KQmCoKAhCqEQAAdScG4DwH4kaJHysYkoSpdCtQaAoOo5wOjkC+qsDs9ttq4iBegEFjCjnsyeQgAAwi0pA8iApeJlJEvi4Au51AYtdOFIKnSkohE0WIUB3onE+DcaocCoRahXGXXiNMq5jVrlgoYFLdr2DCtvRI80poIBuHcHlgNXhQkWl8P4a0ESAh2iCa6UIYSHUxec06wgWabOuoGW6Kx7oBBQLEAGYIzg1xIknT4oJuC2CuNCw+Jx7VylWry4FEJXXqHJZ63a3q+byEktGUeZTdY7lHLclS7hVFkD1uuKNz4rF7IANrCgAFagwABIABUACyAAZAAQn6gAouoFR6AAC6Qla42tIvFbF5k-XaNxd+FAp5zy1utcyPlA9JKN2Hs3Bm48ojLB7ggV5LgY0bC+fPK+uU+VOg+D4FMzb4XUEYQdJwiBHoMqQFkzZihfDG0ZO82NuhvC+BbrGcgNDJU4oid+QqhKnDLpKFE9dZKPUbt2lS91Jw91VAPTSoY9K6EQmZf2ZMIaW4Jm3UgXd3BgMNXrQ+r9EIBVbzIMKqV1AwaOvFVi+aMqPhyp+B0daSqzgqrw7tNVCGxzatRAmvVdGbp8hJKomQFVb18HNZtK1olgDco6AGrdjahgBt9b+qYYAHXKkfm6JmhxrmRqUwUD5VyTaKdDc7ZNiGEBpoaJms0ubC0lt-eWv0Hga1CbriJ5Ozqah8tbU+y2Z4OCoeZHW3tfrZBLqkx+tdfKt2wkM0BrgWTnNubxS+6ob6gurr0YFk4rn-1OkiyB2lNRwOMsg2gaD6hYMjp9AhpD+7vPcpi65rD4VMXSCgKi2M8qp3no2D5ntonqjiadZJl18m3UyZBXJhTJWcnKZGqpnT42ykzrjRG3TcGVIu2sYgYzpm-DmeLWWittnu3Ceq-1lzLaUnts7V5g7DnDB9oEyg7qWCWyTF+aUBrwAnsAc6CuRhYKnDoAk3NE4H3pnA+NH9nAoqPuzaJtUXg5AVDFL5Bt0GAB5EzDYa2Jty9ySAfJocqQyQ2V6t5ZDoD4FQ1xorpj4HkNYRIYgCN8gwU6cnHB6JTGSgD1O-AKdKFPjEnnbO+fJTZdTSuUZSd8EZ4gA64gKi4FZ-RWhJxFdKHcKoFFyuOR-cF2QvrgPteRl1x+IYqvdDq9UNMs3mmNdnwABw2gFtM2X8vIQcDpE6F39H3eBzUuy8XTj-4rhDC8ZwQYg-JhD64MP5knDs+UcMOnWOoipjHPDyMiMlQ4F8HiR1dRrB6UwNYEUABuKA8D8W9j0rQTAmAS+YNFXy4jRYdfW5e-8p0Z38UvASzY2oeMHcCw6UMuZvSCz9OPIM4ZoyLx0gmXzGWAup+j7GYs-70KJaSSlggbAD2Yvp5qG3ooHh7eO8TgAOR9wvPfx3wit957oden4DPP9fNY4+0wAAKpqUKvVP07qmCuCMKMThQMPPMjcgDRCoHSWVZaP4AATQAAp6BWAABSAAShLxZWekDB0jr0wBgIgKgJL1oB0mwJQjxHrxvwNzvyN2t18D9H-0TmvyXn33vyFwrgJV7yYNf1dj71WyUHiyJWzzAL5FgKgMIKWhWiQKLxFEwIIPEKcAqCoNYNvwP2N10E1GiE8HUGWD8F3igkHwkUihfxMLfyUF0PQG-20Jw1ANzzEKIKUJ0lQGKEUEQMIBtFYCEHwHkMkJiGIIvlygPjUPYPZy0IvTk3wD4H0PdmDiMN4OsQSL51fGiOsIvREPsLXCWgkJcL+EQM8O8N8MUM0RUIXUXmCJoPUOt3CM8DzmRB9QMNoCMMCMXjKM6n7Usibg0zCDAHHVcj7k-naOZDJ0l2l35G6DlwVwfy1w0Jt01y9FCL2Wb0N0PwfxZwfzmKtw2It3-xtGdwmNdwNU+3VUmI41FyANpmQWDxPWj3DyB2uNgVuNjyQHjwrUT3xx9GNjTz+0z2VBzzzy1EL2LzLwr0lhFGr1rxUIPEbz9WWNoNWI4JhFUT+RNxOC7yELfUaMHxtGH2n3mRlwGVmRGXmXGT2EmUX0JJH2JLH34FNXX3Fn2DBMQF31UMqMWPN2P1UV2JkBzQJBIBYIqO5yqI2KfzML4KSMfxPmSm-0oFgXwyxMdz2MAL4mAMEjsPAOyKcNgOkOQLQMwPINwPwL8MgKUJILIP7BwMoMwTYLoI2IYIqG5KGMFJXmFMRIxP4IH0VIlIlO71fU1X+IcM1M0WNJ1NkKKMcJKOtJCNtMRJqIsLjBiP7ziK9LFMSNTPjL0LSJ0AyI1P8KcNyLcI8K8JIB8JLwUIjOUJaOoKFPZMohQBsN0CvGiN2O9PTMbJSKsPrPSPVMDLzODILJIHyOLNLPLKDMrKdL8mjIRLCK7NqMEAaNiOtGxKrJYLaLynEkHmKgfj01HV6InQGK8jXMMBGPeyl1FS9zNxmLb1zB+xbxjL1zhNdOzlN22NzC2MRJ2IVMIFYH2PLFd0KCEE9wON2gAt9xDDF1VNcQj0mBuLDyuMj1govCFBeKUAT3zw+LBFT3OQP1+JzLEMBKgFkJBMr3BKgBrzrwb3BkQCb3QyfLVyKBROJTRLbV9O4K-PYHOWX2pL6SXyJJn1JKqQX3uEpLxJpLX0YU33bGZKjLZPvPotjS5PYpkFRQeX5LXOdPIlrNFItFMJ0vMMlK-x-zlPOHYvOJVNpjwqyL7OgO1IQN1IwKwItIoLwLLONOINIINKtOrJdNrPtP-3YAnJ9h8rks4J7yJX8tbL0r4NYuEJ7KspNODNssUBkOL3DLHKhMnNkunKUDjMvQTIirbJ9MsKzNsIDPipyIwDyKLMKNcuKPHIFMyprJCrrIbMiObNMsKrbLas7IbMsrTDHOcMqrcIKJLLSustKMyg0qbTos0NnKUDqJAAXKTKXMdwCtXOvlylvk3K6J3J9B6L6N7nXHnUvhPLJzGIvOmPWI-JvOhTBxCq52CuyqYqes2IF2vNty-IADZfzTiVFxAgK-zdo-qzKOV4h4KYLHi4LoK+ZELnjXi-R3jk8vjsKfjFIvk4rRACKiLy8SKISKKHsYTf1Hzaz29UTH04sB0-T-9PrcSV9x9eKqT+K58yShLpkuL+LxKN9GSt8oUWSpq7qXrjET8vqVz+a7yXrtLLF9KfT14ZTf95TFzDDHdvrlTQa1Syr+rrKQy7KUCHLPKXLRzxqPKnLAwMqgrNLmq-KRbAraLaz3TqbIqpbor3S+q6rtbkrECwzaqKyzbbbmrcqvB8qvrHaBC8rMy5r-TRDyr8yhrBzqrRrvb0rRbGrHrZiA6mzEyoolbCAVaoq0y87kioieruyNa3aByhyarDaEr6r1KU6LaXqA6Fqlqs6mjlaVyjyb4NyB174R5ls9qiA9z+ijrBjVyTz8owhSaAUjAxAzIJ6GLXtDyycKdSchQQAgwqdkoacVA6dScGIN6Zhl1Od9dud+cLZT5VaA86ZuiiB-JkczQ0dNs7N3tKcqL+RcwZiLcHrgIdiBcdj-5zF5MnbEjf7gK3cPchgvcwGwLy5zLOUMKBLqlJ03l5sGJ0ajl2b8SJ8ZlGaSTmbBLCAxY2a+KSTOaZAoA2sUGoAkYoBhiQAzJJ6vJ0AX7HULcP6bq4Sf6LZOHjxIGjiAbTi+GL7IKZAz0UHeTCRL86QUclRaHSdmGIZ37Pd2H0NuHXquHQHQL+H-zVKQbL6RHkGtNKRQLKQkZZHn7zrFGIHlGj0KlYFUxRGtNWJr0hbPFylPoOG3zf7PH1HAa3H-qIHQHgahGLLgYdoxiiN0MwnSMpD5VKNFVNpaMLUCt1UjojlmNdVYdsR2Mji7puNpB7lYxKRTx0ABMgYzHx6b757-lF6gF3s97X7mcpMj64TT7jxz6-cIKLLk8J7G076-AH6Md6d5GZdLGThP7j6V5VG-6gcAG7BQ6frXdcAfctHvcPdgm4Hk88HEGKGtNmxHBabuL6aRK6aEGE5hLJ9iGxK6SSdyGDGL09mUAaHjy6H1ykTigF7WomGLGNc2GNcv6m0pnvGeHQG+GAnfHBGOmLi4HpAHGL1xGSBJGSAc1HAzGvnzzRmahxmPHbcvGcWfHTjNGwWCWdH1mJdYWdAjHVLKR0AUXnm5HvnVBfn5ibGT17G7mdCfBMXj9XG-rsXLdcX+X8XXdgaiXhXhB-rSXq5xo6NwmZpInpV3gYmKM-h4nlUYVknGMtVBAdUDILpMn9U+Tcn0AyRgkim4hSnLVyn8g57kSPnp7amKm3nGKvJHWGGv50BV68RScSQMAxjqdac+rdgqI8Q9JFQSAy8hQN1oDCLgScawSIT690MPso8w9vlrXKnbXqn3WfW0gPshihh+xrwlnwrRUt6dQ4TC3ohuCoF1AYE4F4EcTk91ACAyc6B4HC2+YmSd9238HKB4E+RyL4GkQ+YO3wgwB+2WYNM71kptEZxr1WgTtf0lh9ZvLgJK3i2nA9BPBJ6ZLud13e8nXXs02Cpu6tze7Ss24B6DqZt54xaah92iUphPhJlqJjK5FV2m0H3N2yNJlkUyHS5ABkAjIqoeWGA5YNSySb-T9QksNYQBopi3RMpurZme6AsXmYLaqSrcfaWYgFfHy12lWAoDUXYwg4wz-W0lAzpVwAZWMr2hZWTGGwhHDV0eEc2YqRZsQAADE52iFBL4Hw1J3dr72jLicEB9gO0VYvB9gXQuOeOoAO2MQVN410Q0MasW06shUiIIAeFcOSB7Ai0UBebCKoB6A9jTOcAztvsZt0Mv2wwzhEh+wzrUw80mjGAbRS5aBPq2AABOAtWgfmRgO3JBBgVQG0HzjwnzvzgAdigE+sBG+oS9i-gTzQS74HoAgAYCzU+vgSEkc74Brm0-szQzE0G0dRadK+ONc2kx-RGwDQ5zsSvqE+GhXFTH1mTxQeU6WwvaAdTQzWzXzR2ysz21USfuEi6yc1v1cy7wk8828zG+Exu381ebdY6MHW3L7svbHX3OHq8lI52jI5g8NXg9v0Q64PCv-tQ8AfQ8A0w43d0Bw7w9o8ehIFw5UESc2jI8Y-I+pRy0lGo4g3o0K1ZRq6Y6U8a429OcQE-1jFe8iXk74+TwE91fbZE83TE6FFIDHGRSh5h6oDh4U6gCR5Xcc1tTU9kw05wy0507AD04M6M8dFM5M8bcs+TDUwNFv1s82gc+qCl2c9oFYDc9Lii8F7872Li5zti8l++pYHc8rBF5r0C4kQYBy6MDy4K-wCK5J9BR6wq-+akwq6+9GyGxB-9Qq-q+DUR7B8E4h469a4TQ01DvWz67MwG8sxBWs0rVG98yOxoKm5Ypm67U18W9-XoaqbKACz9XVag9-UO75GO5oNO7CsSxQ-WCu5fww6LYPYe-wHw8hF7GI8g8+5N-Mgo9+7y1o6g2B7SxbXDXga2b5HP3z-h-fH46t+R+T01FlNE-E8x-OWx4QEb88Wb4ujb+J59+51q0FUp5E206gF0-08M+ZOM8Z-M82DbSs9nnZ5oM552m56c8QBc8dE+oLTtx86gGF-c7IoC9oBi5C4i9YDtygDC9YF85rzIrt1UE+pzpV+ZDV580K86yHZk4JXBTHrwGwKZDe1XavrJjq5Bpwe3XInvbya629re3XR3kZmd5bZXeu2GzCNyuyqdJup2f3hdjm6+Zg+IKUPpm3D7AA9usKaDhvlg7x9ucifKmhd1T5zN0+N3TPthw4C4cc+tHBdlHyL7QCRsGWMvv91z6V8GOxfZjpK3gETZIeCAAtK0mH6t8psnXFHl3zR499JO-fZQSIgJ6ICVOWvdDJP2wxvZyAs-efnTyX4M8zOzPdfqz2s4xYd+9nWQHl0J4H8BeL-c-vL0wDMBH+d-Z-t5yf6Rdb+H-L-pEO-4udUu6XBgE5HoA-9DAf-YSAAPm4OZusL4UARM2AhQDF2tXA3sX1gEqALeGmIwV1wUEoD2+DvAzE73Rwu8LMOAz3vgJMFk8Rs03EgS0PIFshluYfKeq8zvhnth0Cg-att0Mgj0O6uUI8hnyw5OAP2QwP6j10jqZEEAuHSgK2G8C4EoAzGwCYEyCpAoRzrL+JNTrpYNvApAP7lCDsTuBdAyiE-ALjWHiAywqgBZNq1wAww6gecVwCzCRS45d03QFCFIBtrGwGaolMZPX0Pb-I+qawkZGsGcrbCyRibfyASJ8BEiNcpI5EMICYxkiMYD2Fkcc0OanMpkkOWZjIHYTFIpcdSAgA0n4SuJmkwiNpKtAkRoQuAr7WRA1WgDyiLmODGkhyMIjkI-sForCASWtFsjZ87HfBoQxVGXcd6Oze5qY1rqWjUwrIk5hyMFhjFmE8mGQH6I2A0sUA61IIqiIFwB8vMnI2wlRHQBQE9QtjKskAA
