### ISSUE TITLE
Find in Markup Code Editor

### ISSUE THREAD

**Issue by sandrosxila** [testing-library/testing-playground#348]
## Summary 💡

It would be great if we had find in mark-up text feature in markup code editor.

## Examples 🌈

User clicks on markup text editor then presses ctrl + F and finds text in the markup code

## Motivation 🔦

It's very hard to find text with browser find

**Comment by smeijer** [comment]
Sorry, I'm not going to intercept the browser search functionality. If you're using testing-playground for large code samples, you might be better off using the chrome extension.
