### ISSUE TITLE
add "share" dialog / mode

### ISSUE THREAD

**Issue by smeijer** [testing-library/testing-playground#54]
The share dialog should allow us to construct the share URL. Let's start with an "embed" preview builder. We currently don't expose any interface to let the user toggle on/off various panes.

I also want to investigate if we can hookup firebase or a hosted Mongo. Preferably a database with a free level. So we can store sessions in a database, and provide a short URL instead of saving state in the URL as we currently do.

**Comment by marcosvega91** [comment]
Firebase can be good for this purpose

**Comment by Siemko** [comment]
I like the idea, I can start working on that at the weekend. I agree that Firebase is good for this purpose. @smeijer should I set it up?

**Comment by smeijer** [comment]
Sounds great @Siemko!

**Comment by smeijer** [comment]
@Siemko, I hope you haven't put a lot of time in the firebase part already.

If we use github authentication, we can use the gist api to store snippets. That means that we have unlimited free storage. Free version management. And easy authentication. 

That sounds like an better option to me. What do you think?

**Comment by Siemko** [comment]
Don't mention it, I only did some initial setup, so no hard feelings! :innocent: 

GitHub OAuth sounds good to me, I haven't integrated with gists API yet, so that could be a nice challenge! I will have a look at that, you can assign me to that issue, I'm happy to build that integration. :muscle:

**Comment by smeijer** [comment]
Awesome! I'll create an issue for that with a better description in a couple of minutes.

**Comment by MichaelDeBoey** [comment]
If we're using GitHub OAuth, will this mean you can't share the playground without authentication? 🤔

**Comment by smeijer** [comment]
No, it won't. Unauthenticated access will stay possible. 

Authenticated users will just have some additional benefits (saving/loading playgrounds)
