### ISSUE TITLE
add tests

### ISSUE THREAD

**Issue by smeijer** [testing-library/testing-playground#7]
A [testing-playground.com] without tests... I don't think that should be a thing, but at this moment it is.

We should fix that, and use jest & testing-library to do it.

[testing-playground.com]: https://testing-playground.com

**Comment by marcosvega91** [comment]
hey @smeijer have you any preference about folder structure, or configuration?

**Comment by smeijer** [comment]
I usually place my tests next to the files they cover.

Like:

```
./src/components/Editor.js
./src/components/Editor.tests.js
./src/lib/parser.js
./src/lib/parser.tests.js
```

Test config files (if required), I usually place in  `./test`.

But I'm open to suggestions.

**Comment by marcosvega91** [comment]
I usually prefer to separate the things to be clearer but this is a good solution too :)

**Comment by JacobMGEvans** [comment]
I don't mind making Unit Tests, I would like to try out Cypress using your project, if you are cool with that of course.

**Comment by marcosvega91** [comment]
I think that the project need also E2E testing so I think could be ok.

**Comment by smeijer** [comment]
@JacobMGEvans, go for it 👍 I believe it's great to have those tests.

**Comment by JacobMGEvans** [comment]
Awesome! On it.

**Comment by smeijer** [comment]
Closing this one. The test setup was added by #12, and the individual tests will be an ongoing issue.
